### ISSUE TITLE
map() usage

### ISSUE THREAD

**Issue by demidovakatya** [R4meau/46-simple-python-exercises#2]
Hey there, 
I have a question about [exercise 27](https://github.com/R4meau/46-simple-python-exercises/blob/master/exercises/ex27.py).

You wrote:

```
return map(len, words)
```

I wrote the same at first, but I got this:

```
In [4]: map(len, words)
Out[4]: <map at 0x10393c828>
```

This code worked fine:

```
return list(map(len, words))
```

**Comment by demidovakatya** [comment]
p.s. Thanks for this repo! :smile:

**Comment by meaudotme** [comment]
Hi @demidovakatya !
You're welcome! Thanks to you for checking out my repo. 
I tested exercise 27 again and it's working fine (Python 2.7.3). Can you please tell me which version of Python you're using?

**Comment by demidovakatya** [comment]
3.5

**Comment by meaudotme** [comment]
@demidovakatya Ah, well, it must be because you didn't convert the code to Python 3 first, or if you did, you used the file "make_python3.py" which was just a regex way to do it.

Anyways, I removed this file, now you can use "makepython3.py" which uses the 2to3 command (see the section "[Using Python 3?](https://github.com/R4meau/46-simple-python-exercises#using-python-3)" in the README file). 

It will automatically convert

```
return map(len, words)
```

to

```
return list(map(len, words))
```

**Comment by demidovakatya** [comment]
@R4meau, thanks! It's not actually a bug, it's rather a question from a person learning Python. :flushed: I've had some difficulties with `map` in Python 3. Thanks again for explaining this!

**Comment by meaudotme** [comment]
@demidovakatya Ah, well since it wouldn't run normally, I considered it as a bug. But it's fixed now anyways :) And you're welcome.
Cheers,
Nick Rameau.
